/*
This route deletes all the images from cloudinary if image's publicId is not referenced by any document
i.e garbage or unwanted images which are stored in cloudinary and simply wasting space
Such image can be generated by user if they upload it and forget to save image (a database operation saves image metadata in database)
refer image.model.ts for info on metadata
This route must invoked by GitHub actions for every 5 min
and interval limit must be shortened if application gets more traffic and users
*/
import Image from "@/database/models/image.model";
import { v2 as cloudinary, ResourceApiResponse } from "cloudinary";
import { NextResponse } from "next/server";

export async function GET() {
  try {
    const images = await Image.find();
    const publicIds: string[] = [];

    images.map(image => publicIds.push(image.publicId));

    cloudinary.config({
      cloud_name: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
      api_key: process.env.CLOUDINARY_API_KEY,
      api_secret: process.env.CLOUDINARY_API_SECRET,
      secure: true,
    });

    // Convert to Unix timestamp in seconds (5 minutes ago)
    const fiveMinutesAgo = Math.floor(new Date().getTime() / 1000) - 5 * 60;

    // Search for resources older than 5 minutes
    const expression = `uploaded_at<${fiveMinutesAgo}`;
    const { resources } = (await cloudinary.search
      .expression(expression)
      .max_results(50)
      .execute()) as ResourceApiResponse;

    // Filter unwanted images which are not available in database
    const filteredPublicIdsToDelete = resources
      .filter(resource => !publicIds.includes(resource.public_id))
      .map(resource => resource.public_id);
    // if no unwanted resources found then cleanup action is not required, simply end the execution
    if (filteredPublicIdsToDelete.length <= 0)
      return NextResponse.json({ message: "No unwanted resources found" }, { status: 200 });

    await cloudinary.api.delete_resources(filteredPublicIdsToDelete);

    return NextResponse.json({ message: "Unwanted resources deleted from cloudinary" }, { status: 200 });
  } catch (error) {
    console.log("ERROR IN api/cloudinary/cleanup", error);
    return NextResponse.json({ message: (error as Error).message });
  }
}
